version: '3.8'

services:
  python:
    container_name: 05DiscordBot
    build: .
    entrypoint: ["/bin/bash", "-c", "python3 app.py"]
#    volumes:
#      - type: bind
#        source: /home/user01/Docker/CentosSSL/app
#        target: /app
    restart: always
